- 用例编号: case_001
  用例标题: get请求实现登录
  接口地址: login
  是否执行: 是
  token操作: ''
  请求方式: get
  入参关键字: params
  文件对象的参数名: ''
  上传文件路径: ''
  路径参数提取: ''
  依赖数据: ''
  请求数据: '{"username": "admin", "password": ""}'
  预期结果: "{\n        \"msg\": \"参数错误\",\n        \"status\": 400\n    }"
- 用例编号: case_002
  用例标题: post请求实现登录
  接口地址: login
  是否执行: 是
  token操作: 写
  请求方式: post
  入参关键字: data
  文件对象的参数名: ''
  上传文件路径: ''
  路径参数提取: ''
  依赖数据: ''
  请求数据: '{"username": "admin", "password": "123456"}'
  预期结果: "{\n        \"msg\": \"登录成功\",\n        \"status\": 200\n    }"
- 用例编号: case_003
  用例标题: get请求查询用户数据列表
  接口地址: users
  是否执行: 是
  token操作: 读
  请求方式: get
  入参关键字: params
  文件对象的参数名: ''
  上传文件路径: ''
  路径参数提取: ''
  依赖数据: "{\"case_002\": [\"$.data.id\"],\n\"case_001\":[\"$.meta.msg\",\"$.meta.status\"\
    ]}"
  请求数据: '{"pagenum": 1, "pagesize": "12"}'
  预期结果: '{"msg": "获取管理员列表成功", "status": 200}'
- 用例编号: case_004
  用例标题: get请求查询用户数据列表
  接口地址: users
  是否执行: 是
  token操作: ''
  请求方式: get
  入参关键字: data
  文件对象的参数名: ''
  上传文件路径: ''
  路径参数提取: ''
  依赖数据: ''
  请求数据: '{"pagenum": 1, "pagesize": "12"}'
  预期结果: '{"msg": "获取管理员列表成功", "status": 200}'
- 用例编号: case_005
  用例标题: 添加用户正常接口数据
  接口地址: users
  是否执行: 是
  token操作: 读
  请求方式: post
  入参关键字: data
  文件对象的参数名: ''
  上传文件路径: ''
  路径参数提取: ''
  依赖数据: ''
  请求数据: '{"username": "zy7y1234","password": "123456"}'
  预期结果: '{"msg":"创建成功","status":201}'
- 用例编号: case_006
  用例标题: 修改用户状态接口
  接口地址: users
  是否执行: 是
  token操作: 读
  请求方式: put
  入参关键字: data
  文件对象的参数名: ''
  上传文件路径: ''
  路径参数提取: /{"case_005":"$.data.id"}/state/{"case_005":"$.data.create_time"}
  依赖数据: ''
  请求数据: ''
  预期结果: '{"msg": "设置状态成功", "status": 200}'
- 用例编号: case_007
  用例标题: 修改用户状态为2
  接口地址: users
  是否执行: 是
  token操作: 读
  请求方式: put
  入参关键字: data
  文件对象的参数名: ''
  上传文件路径: ''
  路径参数提取: /{"case_005":"$.data.id"}/state/2
  依赖数据: ''
  请求数据: ''
  预期结果: '{"msg": "设置状态成功", "status": 200}'
- 用例编号: case_008
  用例标题: 删除用户zy7y
  接口地址: users
  是否执行: 是
  token操作: 读
  请求方式: delete
  入参关键字: params
  文件对象的参数名: ''
  上传文件路径: ''
  路径参数提取: /{"case_005":"$.data.id"}
  依赖数据: ''
  请求数据: ''
  预期结果: '{"msg": "删除成功", "status": 200}'
