- 用例编号: case_1
  用例标题: 错误的账号，正确的密码
  接口地址: adminLogin
  请求方式: post
  文件对象的参数名: ''
  上传文件路径: ''
  依赖数据: ''
  请求数据: '{"username":"admin","password":"aaaaaaaaaa"}'
  code校验: $..retCode==200
  是否执行: yes
  是否需要token: no
  是否需要上传文件: no
